[package]
name = "xfbin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#  used for reading and writing binary files
binrw = "0.10.0"
